//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CopaMundivox.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CupResult
    {
        public int Id { get; set; }
        public int CupId { get; set; }
        public int TeamAId { get; set; }
        public Nullable<int> TeamAScore { get; set; }
        public int TeambId { get; set; }
        public Nullable<int> TeambScore { get; set; }
        public Nullable<int> WinnerId { get; set; }
        public string TeamAGroup { get; set; }
        public string TeamBGroup { get; set; }
    
        public virtual Cup Cup { get; set; }
        public virtual Team Team { get; set; }
        public virtual Team Team1 { get; set; }
        public virtual Team Team2 { get; set; }
    }
}
